[build-system]
requires = ["setuptools>=40.8.0", "git+https://github.com/Rapptz/discord.py@master#egg=discord.py"]

[tool.pyright]
pythonPlatform = "Linux"
reportUnnecessaryTypeIgnoreComment = true
exclude = ["**/__pycache__/**", "venv"]

[tool.black]
line-length = 120
target-version = ['py310']
